import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function Footer({ onLegalLink }) {
    const handleLegalClick = (e, page) => {
        e.preventDefault();
        if (onLegalLink)
            onLegalLink(page);
    };
    const scrollTo = (anchor) => (e) => {
        e.preventDefault();
        document.querySelector(anchor)?.scrollIntoView({ behavior: "smooth" });
    };
    return (_jsx("footer", { className: "footer", id: "footer", children: _jsx("div", { className: "container", children: _jsxs("div", { className: "footer-grid", children: [_jsxs("div", { className: "footer-col footer-about", children: [_jsx("div", { className: "footer-company", children: "Recrutop \u2013 Int\u00E9rim & recrutement par fili\u00E8res m\u00E9tiers" }), _jsxs("div", { className: "footer-info", children: [_jsx("div", { children: "141 avenue de Clichy, 75017 Paris" }), _jsx("div", { children: _jsx("a", { href: "tel:0140242040", children: "01 40 24 20 40" }) }), _jsx("div", { children: _jsx("a", { href: "mailto:contact@recrutop.fr", children: "contact@recrutop.fr" }) })] }), _jsxs("div", { className: "footer-social", children: [_jsx("h4", { className: "footer-title", children: "R\u00E9seaux sociaux" }), _jsx("div", { className: "footer-social-links", children: _jsx("a", { href: "https://www.linkedin.com/company/recrutop", target: "_blank", rel: "noopener noreferrer", "aria-label": "LinkedIn Recrutop", children: "LinkedIn" }) })] })] }), _jsxs("div", { className: "footer-col footer-links-block", children: [_jsx("h4", { className: "footer-title", children: "Nos fili\u00E8res m\u00E9tiers" }), _jsx("a", { href: "#fili\u00E8res", onClick: scrollTo("#filières"), children: "Toutes les fili\u00E8res" })] }), _jsxs("div", { className: "footer-col footer-links-block", children: [_jsx("h4", { className: "footer-title", children: "Passerelle (Insertion)" }), _jsx("a", { href: "#insertion", onClick: scrollTo("#insertion"), children: "D\u00E9couvrir Passerelle" }), _jsx("a", { href: "https://passerelle-insertion.fr", target: "_blank", rel: "noopener noreferrer", children: "Site Passerelle" })] }), _jsxs("div", { className: "footer-col footer-legal", children: [_jsx("h4", { className: "footer-title", children: "Informations" }), _jsx("a", { href: "#", onClick: (e) => handleLegalClick(e, "mentions-legales"), children: "Mentions l\u00E9gales / RGPD" }), _jsx("a", { href: "https://recrutement.recrutop.fr/", target: "_blank", rel: "noopener noreferrer", children: "Recrutement" }), _jsx("a", { href: "#", onClick: (e) => handleLegalClick(e, "politique-confidentialite"), children: "Politique de confidentialit\u00E9" }), _jsx("a", { href: "#", onClick: (e) => handleLegalClick(e, "accessibilite"), children: "Accessibilit\u00E9" })] })] }) }) }));
}
export default Footer;
